name: cpp-tools-workflows
on:   
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Step
        run: echo "BUILD START !!!!"
      - name: Build Run Clean
        run: make run clean
        working-directory: lev_distance
