name: cpp-tools-workflows
on:   
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "START !!!!"
      - name: pwd
        run: pwd
      - name: cd
        run: cd /home/runner/work/cpp-tools/lev_distance
      - name: Build Run 2
        run: make run
        working-directory: lev_distance
